name: Releases

on:
  push:
    branches:
      - master

jobs:
  windows_build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: rqiner-benchmark-win
        path: D:\a\RqinerBenchmark\RqinerBenchmark\RqinerBenchmark\bin\Release\net8.0\win-x64\publish\

  macos_build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: rqiner-benchmark-macos
        path: /Users/runner/work/RqinerBenchmark/RqinerBenchmark/RqinerBenchmark/bin/Release/net8.0/osx-x64/publish/

  linux_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: rqiner-benchmark-linux
        path: /home/runner/work/RqinerBenchmark/RqinerBenchmark/RqinerBenchmark/bin/Release/net8.0/linux-x64/publish/
